# Generated by Django 4.0 on 2021-12-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_food_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customerNumber',
            new_name='username',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='store.Food'),
        ),
        migrations.AddField(
            model_name='orderfood',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
